version: '3.8'

services:
  backend:
    image: mpierangeli/fs_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - test-network
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
